widgets:
- category
- tagcloud
- archive
- search_duck


sitemap1:
  ホーム: /
  カテゴリー: /category/
  アーカイブ: /archive/
  検索: /search/

sitemap2:
  プロフィール: /about/
  お問い合わせ: /contact/
  プライバシーポリシー: /privacy/
  RSS: /atom.xml
