widgets:
  - category
  - tagcloud
  - archive
  - recent_posts
  - link
  - search


category:
  name: Categories

tagcloud:
  name: Tags

archive:
  name: Archive

recent_posts:
  name: Recent Posts
  amount: 5

link:
  name: Links
  list:
    サイトについて: /about/
    RSS: /atom.xml

search:
  name: Search
