widgets:
  - category
  - tagcloud
  - archive


nav:
  サイトについて: /about/
  RSS: /atom.xml


category:
  name: Category

tagcloud:
  name: Tag

archive:
  name: Archive

recent_posts:
  name: 最近の投稿
  amount: 5

link:
  name: リンク
  list:
    サイトについて: /about/
    RSS: /atom.xml

search:
  name: 検索
