widgets:
  - category
  - tagcloud
  - archive



category:
  name: カテゴリー

tagcloud:
  name: タグ

archive:
  name: アーカイブ

recent_posts:
  name: 最近の投稿
  amount: 5

link:
  name: リンク
  list:
    サイトについて: /about/
    RSS: /atom.xml

search:
  name: 検索
